version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "prod-QueryResultLambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-84hyntz8n79r"
s3_prefix = "prod-QueryResultLambda"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"prod\""

