// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "us-west-2",
  "aws_cognito_identity_pool_id": "us-west-2:29abd96b-7b57-4133-9aa6-04ca7c1d288c",
  "aws_cognito_region": "us-west-2",
  // "aws_user_pools_id": "us-west-2_yfPL1xn8U",
  // "aws_user_pools_web_client_id": "587a632dputjhdt1u7sqpn4vcg"
};

export default awsmobile;
