// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:29abd96b-7b57-4133-9aa6-04ca7c1d288c",
    "aws_cognito_region": "us-west-2"
};

export default awsmobile;
