// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:2514e49c-af4b-4642-8ce0-4736e6a4a3bb",
    "aws_cognito_region": "us-west-2"
};

export default awsmobile;
